spring.application.name=beauty-salon

# ???????????? ??????????? ?? ??
spring.datasource.url=jdbc:postgresql://localhost:5432/beauty_salon_db
spring.datasource.username=postgres
spring.datasource.password=251723

# ???????????? Hibernate (??????????? ??????? ??????? ?? ?????)
spring.jpa.hibernate.ddl-auto=update

# ??? ?????? ? ???????, ??? SQL-?????? ?????? ????????
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true